name: Build and Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [[ubuntu-latest, linux64, ""], [windows-latest, win64, ".exe"], [macos-latest, macos-intel, ""], [macos-arm64, macos-arm, ""]]
    runs-on: ${{ matrix.os[0] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build release
        run: >-
          cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository.name }}-${{ matrix.os[1] }}${{ matrix.os[2] }}
          path: ./target/release/${{ github.repository.name }}${{ matrix.os[2] }}
  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  #       with:
  #         tag_name: '${{ github.ref }}'
  #         release_name: 'Release ${{ github.ref }}'
  #         draft: false
  #         prerelease: false
